// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

package com.github.difftim.friend;

/**
 * Protobuf type {@code pb.HowToMetRequest}
 */
public  final class HowToMetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.HowToMetRequest)
    HowToMetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HowToMetRequest.newBuilder() to construct.
  private HowToMetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HowToMetRequest() {
    src_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    dst_ = "";
    lang_ = "";
    sourceQueryType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HowToMetRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HowToMetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              src_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            src_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dst_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lang_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceQueryType_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        src_ = src_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.difftim.friend.FriendProto.internal_static_pb_HowToMetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.difftim.friend.FriendProto.internal_static_pb_HowToMetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.difftim.friend.HowToMetRequest.class, com.github.difftim.friend.HowToMetRequest.Builder.class);
  }

  public static final int SRC_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList src_;
  /**
   * <code>repeated string src = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getSrcList() {
    return src_;
  }
  /**
   * <code>repeated string src = 1;</code>
   */
  public int getSrcCount() {
    return src_.size();
  }
  /**
   * <code>repeated string src = 1;</code>
   */
  public java.lang.String getSrc(int index) {
    return src_.get(index);
  }
  /**
   * <code>repeated string src = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSrcBytes(int index) {
    return src_.getByteString(index);
  }

  public static final int DST_FIELD_NUMBER = 2;
  private volatile java.lang.Object dst_;
  /**
   * <code>string dst = 2;</code>
   */
  public java.lang.String getDst() {
    java.lang.Object ref = dst_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dst_ = s;
      return s;
    }
  }
  /**
   * <code>string dst = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDstBytes() {
    java.lang.Object ref = dst_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dst_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANG_FIELD_NUMBER = 3;
  private volatile java.lang.Object lang_;
  /**
   * <code>string lang = 3;</code>
   */
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lang_ = s;
      return s;
    }
  }
  /**
   * <code>string lang = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEQUERYTYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object sourceQueryType_;
  /**
   * <code>string sourceQueryType = 4;</code>
   */
  public java.lang.String getSourceQueryType() {
    java.lang.Object ref = sourceQueryType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceQueryType_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceQueryType = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSourceQueryTypeBytes() {
    java.lang.Object ref = sourceQueryType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceQueryType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < src_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, src_.getRaw(i));
    }
    if (!getDstBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dst_);
    }
    if (!getLangBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lang_);
    }
    if (!getSourceQueryTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sourceQueryType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < src_.size(); i++) {
        dataSize += computeStringSizeNoTag(src_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSrcList().size();
    }
    if (!getDstBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dst_);
    }
    if (!getLangBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lang_);
    }
    if (!getSourceQueryTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sourceQueryType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.difftim.friend.HowToMetRequest)) {
      return super.equals(obj);
    }
    com.github.difftim.friend.HowToMetRequest other = (com.github.difftim.friend.HowToMetRequest) obj;

    if (!getSrcList()
        .equals(other.getSrcList())) return false;
    if (!getDst()
        .equals(other.getDst())) return false;
    if (!getLang()
        .equals(other.getLang())) return false;
    if (!getSourceQueryType()
        .equals(other.getSourceQueryType())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSrcCount() > 0) {
      hash = (37 * hash) + SRC_FIELD_NUMBER;
      hash = (53 * hash) + getSrcList().hashCode();
    }
    hash = (37 * hash) + DST_FIELD_NUMBER;
    hash = (53 * hash) + getDst().hashCode();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + getLang().hashCode();
    hash = (37 * hash) + SOURCEQUERYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceQueryType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.difftim.friend.HowToMetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.difftim.friend.HowToMetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.difftim.friend.HowToMetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.difftim.friend.HowToMetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.HowToMetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.HowToMetRequest)
      com.github.difftim.friend.HowToMetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.difftim.friend.FriendProto.internal_static_pb_HowToMetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.difftim.friend.FriendProto.internal_static_pb_HowToMetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.difftim.friend.HowToMetRequest.class, com.github.difftim.friend.HowToMetRequest.Builder.class);
    }

    // Construct using com.github.difftim.friend.HowToMetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      src_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      dst_ = "";

      lang_ = "";

      sourceQueryType_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.difftim.friend.FriendProto.internal_static_pb_HowToMetRequest_descriptor;
    }

    @java.lang.Override
    public com.github.difftim.friend.HowToMetRequest getDefaultInstanceForType() {
      return com.github.difftim.friend.HowToMetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.difftim.friend.HowToMetRequest build() {
      com.github.difftim.friend.HowToMetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.difftim.friend.HowToMetRequest buildPartial() {
      com.github.difftim.friend.HowToMetRequest result = new com.github.difftim.friend.HowToMetRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        src_ = src_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.src_ = src_;
      result.dst_ = dst_;
      result.lang_ = lang_;
      result.sourceQueryType_ = sourceQueryType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.difftim.friend.HowToMetRequest) {
        return mergeFrom((com.github.difftim.friend.HowToMetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.difftim.friend.HowToMetRequest other) {
      if (other == com.github.difftim.friend.HowToMetRequest.getDefaultInstance()) return this;
      if (!other.src_.isEmpty()) {
        if (src_.isEmpty()) {
          src_ = other.src_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSrcIsMutable();
          src_.addAll(other.src_);
        }
        onChanged();
      }
      if (!other.getDst().isEmpty()) {
        dst_ = other.dst_;
        onChanged();
      }
      if (!other.getLang().isEmpty()) {
        lang_ = other.lang_;
        onChanged();
      }
      if (!other.getSourceQueryType().isEmpty()) {
        sourceQueryType_ = other.sourceQueryType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.difftim.friend.HowToMetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.difftim.friend.HowToMetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList src_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSrcIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        src_ = new com.google.protobuf.LazyStringArrayList(src_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSrcList() {
      return src_.getUnmodifiableView();
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public int getSrcCount() {
      return src_.size();
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public java.lang.String getSrc(int index) {
      return src_.get(index);
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes(int index) {
      return src_.getByteString(index);
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public Builder setSrc(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSrcIsMutable();
      src_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public Builder addSrc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSrcIsMutable();
      src_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public Builder addAllSrc(
        java.lang.Iterable<java.lang.String> values) {
      ensureSrcIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, src_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public Builder clearSrc() {
      src_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string src = 1;</code>
     */
    public Builder addSrcBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSrcIsMutable();
      src_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object dst_ = "";
    /**
     * <code>string dst = 2;</code>
     */
    public java.lang.String getDst() {
      java.lang.Object ref = dst_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dst_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dst = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDstBytes() {
      java.lang.Object ref = dst_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dst = 2;</code>
     */
    public Builder setDst(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dst_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dst = 2;</code>
     */
    public Builder clearDst() {
      
      dst_ = getDefaultInstance().getDst();
      onChanged();
      return this;
    }
    /**
     * <code>string dst = 2;</code>
     */
    public Builder setDstBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dst_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lang_ = "";
    /**
     * <code>string lang = 3;</code>
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lang = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lang = 3;</code>
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lang_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 3;</code>
     */
    public Builder clearLang() {
      
      lang_ = getDefaultInstance().getLang();
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 3;</code>
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lang_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceQueryType_ = "";
    /**
     * <code>string sourceQueryType = 4;</code>
     */
    public java.lang.String getSourceQueryType() {
      java.lang.Object ref = sourceQueryType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceQueryType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceQueryType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSourceQueryTypeBytes() {
      java.lang.Object ref = sourceQueryType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceQueryType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceQueryType = 4;</code>
     */
    public Builder setSourceQueryType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceQueryType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceQueryType = 4;</code>
     */
    public Builder clearSourceQueryType() {
      
      sourceQueryType_ = getDefaultInstance().getSourceQueryType();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceQueryType = 4;</code>
     */
    public Builder setSourceQueryTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceQueryType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.HowToMetRequest)
  }

  // @@protoc_insertion_point(class_scope:pb.HowToMetRequest)
  private static final com.github.difftim.friend.HowToMetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.difftim.friend.HowToMetRequest();
  }

  public static com.github.difftim.friend.HowToMetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HowToMetRequest>
      PARSER = new com.google.protobuf.AbstractParser<HowToMetRequest>() {
    @java.lang.Override
    public HowToMetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HowToMetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HowToMetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HowToMetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.difftim.friend.HowToMetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

