// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

package com.github.difftim.friend;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.BaseResponse base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>.pb.BaseResponse base = 1;</code>
   */
  com.github.difftim.common.BaseResponse getBase();
  /**
   * <code>.pb.BaseResponse base = 1;</code>
   */
  com.github.difftim.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>string pong = 2;</code>
   */
  java.lang.String getPong();
  /**
   * <code>string pong = 2;</code>
   */
  com.google.protobuf.ByteString
      getPongBytes();
}
