// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalTeamsService.proto

package org.whispersystems.textsecuregcm.internal.teams;

public interface GetTreeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTreeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated bool status = 2;</code>
   */
  java.util.List<java.lang.Boolean> getStatusList();
  /**
   * <code>repeated bool status = 2;</code>
   */
  int getStatusCount();
  /**
   * <code>repeated bool status = 2;</code>
   */
  boolean getStatus(int index);
}
