// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.github.difftim.register;

public interface SendSMSResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SendSMSResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.BaseResponse base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>.pb.BaseResponse base = 1;</code>
   */
  com.github.difftim.common.BaseResponse getBase();
  /**
   * <code>.pb.BaseResponse base = 1;</code>
   */
  com.github.difftim.common.BaseResponseOrBuilder getBaseOrBuilder();
}
