// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsInvitationService.proto

package org.whispersystems.textsecuregcm.internal.invitation;

public interface GenerateInvitationCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateInvitationCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string email = 1;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string inviter = 2;</code>
   */
  boolean hasInviter();
  /**
   * <code>optional string inviter = 2;</code>
   */
  java.lang.String getInviter();
  /**
   * <code>optional string inviter = 2;</code>
   */
  com.google.protobuf.ByteString
      getInviterBytes();

  /**
   * <code>optional string name = 3;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string number = 4;</code>
   */
  boolean hasNumber();
  /**
   * <code>optional string number = 4;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>optional string number = 4;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>optional string account = 5;</code>
   */
  boolean hasAccount();
  /**
   * <code>optional string account = 5;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>optional string account = 5;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>optional string oktaId = 6;</code>
   */
  boolean hasOktaId();
  /**
   * <code>optional string oktaId = 6;</code>
   */
  java.lang.String getOktaId();
  /**
   * <code>optional string oktaId = 6;</code>
   */
  com.google.protobuf.ByteString
      getOktaIdBytes();

  /**
   * <code>optional string orgs = 7;</code>
   */
  boolean hasOrgs();
  /**
   * <code>optional string orgs = 7;</code>
   */
  java.lang.String getOrgs();
  /**
   * <code>optional string orgs = 7;</code>
   */
  com.google.protobuf.ByteString
      getOrgsBytes();

  /**
   * <code>optional string backup1 = 8;</code>
   */
  boolean hasBackup1();
  /**
   * <code>optional string backup1 = 8;</code>
   */
  java.lang.String getBackup1();
  /**
   * <code>optional string backup1 = 8;</code>
   */
  com.google.protobuf.ByteString
      getBackup1Bytes();

  /**
   * <code>optional string oktaOrg = 9;</code>
   */
  boolean hasOktaOrg();
  /**
   * <code>optional string oktaOrg = 9;</code>
   */
  java.lang.String getOktaOrg();
  /**
   * <code>optional string oktaOrg = 9;</code>
   */
  com.google.protobuf.ByteString
      getOktaOrgBytes();
}
