// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.github.difftim.accountgrpc;

public final class AccountOuterClass {
  private AccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SyncProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SyncProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SyncProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SyncProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GenEmailVcodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GenEmailVcodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GenEmailVcodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GenEmailVcodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CheckEmailVcodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CheckEmailVcodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CheckEmailVcodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CheckEmailVcodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_HashUserMetaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_HashUserMetaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_HashUserMetaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_HashUserMetaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DelUserHashRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DelUserHashRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DelUserHashResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DelUserHashResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_InitUserProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_InitUserProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_InitUserProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_InitUserProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GetUserProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GetUserProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GetUserProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GetUserProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DisableSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DisableSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DisableSearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DisableSearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DeleteAccReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DeleteAccReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_DeleteAccResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_DeleteAccResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\002pb\032\016commonV3.proto\"e\n\022S" +
      "yncProfileRequest\022\013\n\003uid\030\001 \001(\t\022\r\n\005email\030" +
      "\002 \001(\t\022\r\n\005phone\030\003 \001(\t\022\021\n\temailHash\030\004 \001(\t\022" +
      "\021\n\tphoneHash\030\005 \001(\t\"5\n\023SyncProfileRespons" +
      "e\022\036\n\004base\030\001 \001(\0132\020.pb.BaseResponse\"%\n\024Gen" +
      "EmailVcodeRequest\022\r\n\005email\030\001 \001(\t\"F\n\025GenE" +
      "mailVcodeResponse\022\036\n\004base\030\001 \001(\0132\020.pb.Bas" +
      "eResponse\022\r\n\005vcode\030\002 \001(\t\"I\n\026CheckEmailVc" +
      "odeRequest\022\r\n\005email\030\001 \001(\t\022\021\n\temailHash\030\002" +
      " \001(\t\022\r\n\005vcode\030\003 \001(\t\"9\n\027CheckEmailVcodeRe" +
      "sponse\022\036\n\004base\030\001 \001(\0132\020.pb.BaseResponse\"3" +
      "\n\023HashUserMetaRequest\022\r\n\005email\030\001 \001(\t\022\r\n\005" +
      "phone\030\002 \001(\t\"\\\n\024HashUserMetaResponse\022\036\n\004b" +
      "ase\030\001 \001(\0132\020.pb.BaseResponse\022\021\n\temailHash" +
      "\030\002 \001(\t\022\021\n\tphoneHash\030\003 \001(\t\"E\n\022DelUserHash" +
      "Request\022\013\n\003uid\030\001 \001(\t\022\020\n\010delEmail\030\002 \001(\010\022\020" +
      "\n\010delPhone\030\003 \001(\010\"5\n\023DelUserHashResponse\022" +
      "\036\n\004base\030\001 \001(\0132\020.pb.BaseResponse\"K\n\026InitU" +
      "serProfileRequest\022\013\n\003uid\030\001 \001(\t\022\021\n\temailH" +
      "ash\030\002 \001(\t\022\021\n\tphoneHash\030\003 \001(\t\"9\n\027InitUser" +
      "ProfileResponse\022\036\n\004base\030\001 \001(\0132\020.pb.BaseR" +
      "esponse\"h\n\025GetUserProfileRequest\022\013\n\003uid\030" +
      "\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\r\n\005phone\030\003 \001(\t\022\021\n\te" +
      "mailHash\030\004 \001(\t\022\021\n\tphoneHash\030\005 \001(\t\"k\n\026Get" +
      "UserProfileResponse\022\036\n\004base\030\001 \001(\0132\020.pb.B" +
      "aseResponse\022\013\n\003uid\030\002 \001(\t\022\021\n\temailHash\030\003 " +
      "\001(\t\022\021\n\tphoneHash\030\004 \001(\t\"#\n\024DisableSearchR" +
      "equest\022\013\n\003uid\030\001 \001(\t\"7\n\025DisableSearchResp" +
      "onse\022\036\n\004base\030\001 \001(\0132\020.pb.BaseResponse\"\033\n\014" +
      "DeleteAccReq\022\013\n\003uid\030\001 \001(\t\"/\n\rDeleteAccRe" +
      "sp\022\036\n\004base\030\001 \001(\0132\020.pb.BaseResponse2\205\005\n\007A" +
      "ccount\022>\n\013SyncProfile\022\026.pb.SyncProfileRe" +
      "quest\032\027.pb.SyncProfileResponse\022O\n\030GenEma" +
      "ilVerificationCode\022\030.pb.GenEmailVcodeReq" +
      "uest\032\031.pb.GenEmailVcodeResponse\022U\n\032Check" +
      "EmailVerificationCode\022\032.pb.CheckEmailVco" +
      "deRequest\032\033.pb.CheckEmailVcodeResponse\022A" +
      "\n\014HashUserMeta\022\027.pb.HashUserMetaRequest\032" +
      "\030.pb.HashUserMetaResponse\022J\n\017InitUserPro" +
      "file\022\032.pb.InitUserProfileRequest\032\033.pb.In" +
      "itUserProfileResponse\022G\n\016GetUserProfile\022" +
      "\031.pb.GetUserProfileRequest\032\032.pb.GetUserP" +
      "rofileResponse\022>\n\013DelUserHash\022\026.pb.DelUs" +
      "erHashRequest\032\027.pb.DelUserHashResponse\022D" +
      "\n\rDisableSearch\022\030.pb.DisableSearchReques" +
      "t\032\031.pb.DisableSearchResponse\0224\n\rDeleteAc" +
      "count\022\020.pb.DeleteAccReq\032\021.pb.DeleteAccRe" +
      "spB(\n\036com.github.difftim.accountgrpcP\001Z\004" +
      "./pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.difftim.common.CommonProto.getDescriptor(),
        });
    internal_static_pb_SyncProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_SyncProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SyncProfileRequest_descriptor,
        new java.lang.String[] { "Uid", "Email", "Phone", "EmailHash", "PhoneHash", });
    internal_static_pb_SyncProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_SyncProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SyncProfileResponse_descriptor,
        new java.lang.String[] { "Base", });
    internal_static_pb_GenEmailVcodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_GenEmailVcodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GenEmailVcodeRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_pb_GenEmailVcodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_GenEmailVcodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GenEmailVcodeResponse_descriptor,
        new java.lang.String[] { "Base", "Vcode", });
    internal_static_pb_CheckEmailVcodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pb_CheckEmailVcodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CheckEmailVcodeRequest_descriptor,
        new java.lang.String[] { "Email", "EmailHash", "Vcode", });
    internal_static_pb_CheckEmailVcodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pb_CheckEmailVcodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CheckEmailVcodeResponse_descriptor,
        new java.lang.String[] { "Base", });
    internal_static_pb_HashUserMetaRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pb_HashUserMetaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_HashUserMetaRequest_descriptor,
        new java.lang.String[] { "Email", "Phone", });
    internal_static_pb_HashUserMetaResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pb_HashUserMetaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_HashUserMetaResponse_descriptor,
        new java.lang.String[] { "Base", "EmailHash", "PhoneHash", });
    internal_static_pb_DelUserHashRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pb_DelUserHashRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DelUserHashRequest_descriptor,
        new java.lang.String[] { "Uid", "DelEmail", "DelPhone", });
    internal_static_pb_DelUserHashResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pb_DelUserHashResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DelUserHashResponse_descriptor,
        new java.lang.String[] { "Base", });
    internal_static_pb_InitUserProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pb_InitUserProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_InitUserProfileRequest_descriptor,
        new java.lang.String[] { "Uid", "EmailHash", "PhoneHash", });
    internal_static_pb_InitUserProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pb_InitUserProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_InitUserProfileResponse_descriptor,
        new java.lang.String[] { "Base", });
    internal_static_pb_GetUserProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pb_GetUserProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GetUserProfileRequest_descriptor,
        new java.lang.String[] { "Uid", "Email", "Phone", "EmailHash", "PhoneHash", });
    internal_static_pb_GetUserProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pb_GetUserProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GetUserProfileResponse_descriptor,
        new java.lang.String[] { "Base", "Uid", "EmailHash", "PhoneHash", });
    internal_static_pb_DisableSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_pb_DisableSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DisableSearchRequest_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_pb_DisableSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_pb_DisableSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DisableSearchResponse_descriptor,
        new java.lang.String[] { "Base", });
    internal_static_pb_DeleteAccReq_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_pb_DeleteAccReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DeleteAccReq_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_pb_DeleteAccResp_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_pb_DeleteAccResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_DeleteAccResp_descriptor,
        new java.lang.String[] { "Base", });
    com.github.difftim.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
