// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.github.difftim.accountgrpc;

public interface InitUserProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.InitUserProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string emailHash = 2;</code>
   */
  java.lang.String getEmailHash();
  /**
   * <code>string emailHash = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailHashBytes();

  /**
   * <code>string phoneHash = 3;</code>
   */
  java.lang.String getPhoneHash();
  /**
   * <code>string phoneHash = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhoneHashBytes();
}
