// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConversationMsgInfo.proto

package org.whispersystems.textsecuregcm.entities;

public final class ConversationMsgInfos {
  private ConversationMsgInfos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConversationMsgInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:textsecure.ConversationMsgInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *会话信息
     * </pre>
     *
     * <code>optional .textsecure.ConversationId conversationId = 1;</code>
     */
    boolean hasConversationId();
    /**
     * <pre>
     *会话信息
     * </pre>
     *
     * <code>optional .textsecure.ConversationId conversationId = 1;</code>
     */
    org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId getConversationId();
    /**
     * <pre>
     *会话信息
     * </pre>
     *
     * <code>optional .textsecure.ConversationId conversationId = 1;</code>
     */
    org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationIdOrBuilder getConversationIdOrBuilder();

    /**
     * <pre>
     *已读位置，用于计算未读数
     * </pre>
     *
     * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
     */
    boolean hasReadPosition();
    /**
     * <pre>
     *已读位置，用于计算未读数
     * </pre>
     *
     * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
     */
    org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition getReadPosition();
    /**
     * <pre>
     *已读位置，用于计算未读数
     * </pre>
     *
     * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
     */
    org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPositionOrBuilder getReadPositionOrBuilder();

    /**
     * <pre>
     *已读矫正值，用于计算未读数
     * </pre>
     *
     * <code>optional uint32 unreadCorrection = 3;</code>
     */
    boolean hasUnreadCorrection();
    /**
     * <pre>
     *已读矫正值，用于计算未读数
     * </pre>
     *
     * <code>optional uint32 unreadCorrection = 3;</code>
     */
    int getUnreadCorrection();

    /**
     * <pre>
     *最新的一条可见消息，用于消息预览
     * </pre>
     *
     * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
     */
    boolean hasLastestMsg();
    /**
     * <pre>
     *最新的一条可见消息，用于消息预览
     * </pre>
     *
     * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
     */
    org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope getLastestMsg();
    /**
     * <pre>
     *最新的一条可见消息，用于消息预览
     * </pre>
     *
     * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
     */
    org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder getLastestMsgOrBuilder();

    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    java.util.List<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope> 
        getOnePageMsgsList();
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope getOnePageMsgs(int index);
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    int getOnePageMsgsCount();
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    java.util.List<? extends org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> 
        getOnePageMsgsOrBuilderList();
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder getOnePageMsgsOrBuilder(
        int index);

    /**
     * <pre>
     *自己发送的可见消息最大NsId，用于计算未读数
     * </pre>
     *
     * <code>optional uint64 maxOutgoingNsId = 6;</code>
     */
    boolean hasMaxOutgoingNsId();
    /**
     * <pre>
     *自己发送的可见消息最大NsId，用于计算未读数
     * </pre>
     *
     * <code>optional uint64 maxOutgoingNsId = 6;</code>
     */
    long getMaxOutgoingNsId();

    /**
     * <pre>
     *可拉取最老的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgSId = 7;</code>
     */
    boolean hasOldestMsgSId();
    /**
     * <pre>
     *可拉取最老的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgSId = 7;</code>
     */
    long getOldestMsgSId();

    /**
     * <pre>
     *可拉取最老的消息notifySequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgNsId = 8;</code>
     */
    boolean hasOldestMsgNsId();
    /**
     * <pre>
     *可拉取最老的消息notifySequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgNsId = 8;</code>
     */
    long getOldestMsgNsId();

    /**
     * <pre>
     *可拉取最新的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 lastestMsgSId = 9;</code>
     */
    boolean hasLastestMsgSId();
    /**
     * <pre>
     *可拉取最新的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 lastestMsgSId = 9;</code>
     */
    long getLastestMsgSId();
  }
  /**
   * Protobuf type {@code textsecure.ConversationMsgInfo}
   */
  public  static final class ConversationMsgInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:textsecure.ConversationMsgInfo)
      ConversationMsgInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConversationMsgInfo.newBuilder() to construct.
    private ConversationMsgInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConversationMsgInfo() {
      onePageMsgs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConversationMsgInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConversationMsgInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = conversationId_.toBuilder();
              }
              conversationId_ = input.readMessage(org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(conversationId_);
                conversationId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = readPosition_.toBuilder();
              }
              readPosition_ = input.readMessage(org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(readPosition_);
                readPosition_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              unreadCorrection_ = input.readUInt32();
              break;
            }
            case 34: {
              org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = lastestMsg_.toBuilder();
              }
              lastestMsg_ = input.readMessage(org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastestMsg_);
                lastestMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                onePageMsgs_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope>();
                mutable_bitField0_ |= 0x00000010;
              }
              onePageMsgs_.add(
                  input.readMessage(org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.PARSER, extensionRegistry));
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              maxOutgoingNsId_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              oldestMsgSId_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              oldestMsgNsId_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              lastestMsgSId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          onePageMsgs_ = java.util.Collections.unmodifiableList(onePageMsgs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.internal_static_textsecure_ConversationMsgInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.internal_static_textsecure_ConversationMsgInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.class, org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.Builder.class);
    }

    private int bitField0_;
    public static final int CONVERSATIONID_FIELD_NUMBER = 1;
    private org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId conversationId_;
    /**
     * <pre>
     *会话信息
     * </pre>
     *
     * <code>optional .textsecure.ConversationId conversationId = 1;</code>
     */
    public boolean hasConversationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *会话信息
     * </pre>
     *
     * <code>optional .textsecure.ConversationId conversationId = 1;</code>
     */
    public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId getConversationId() {
      return conversationId_ == null ? org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.getDefaultInstance() : conversationId_;
    }
    /**
     * <pre>
     *会话信息
     * </pre>
     *
     * <code>optional .textsecure.ConversationId conversationId = 1;</code>
     */
    public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationIdOrBuilder getConversationIdOrBuilder() {
      return conversationId_ == null ? org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.getDefaultInstance() : conversationId_;
    }

    public static final int READPOSITION_FIELD_NUMBER = 2;
    private org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition readPosition_;
    /**
     * <pre>
     *已读位置，用于计算未读数
     * </pre>
     *
     * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
     */
    public boolean hasReadPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *已读位置，用于计算未读数
     * </pre>
     *
     * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
     */
    public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition getReadPosition() {
      return readPosition_ == null ? org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.getDefaultInstance() : readPosition_;
    }
    /**
     * <pre>
     *已读位置，用于计算未读数
     * </pre>
     *
     * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
     */
    public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPositionOrBuilder getReadPositionOrBuilder() {
      return readPosition_ == null ? org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.getDefaultInstance() : readPosition_;
    }

    public static final int UNREADCORRECTION_FIELD_NUMBER = 3;
    private int unreadCorrection_;
    /**
     * <pre>
     *已读矫正值，用于计算未读数
     * </pre>
     *
     * <code>optional uint32 unreadCorrection = 3;</code>
     */
    public boolean hasUnreadCorrection() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *已读矫正值，用于计算未读数
     * </pre>
     *
     * <code>optional uint32 unreadCorrection = 3;</code>
     */
    public int getUnreadCorrection() {
      return unreadCorrection_;
    }

    public static final int LASTESTMSG_FIELD_NUMBER = 4;
    private org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope lastestMsg_;
    /**
     * <pre>
     *最新的一条可见消息，用于消息预览
     * </pre>
     *
     * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
     */
    public boolean hasLastestMsg() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *最新的一条可见消息，用于消息预览
     * </pre>
     *
     * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
     */
    public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope getLastestMsg() {
      return lastestMsg_ == null ? org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance() : lastestMsg_;
    }
    /**
     * <pre>
     *最新的一条可见消息，用于消息预览
     * </pre>
     *
     * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
     */
    public org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder getLastestMsgOrBuilder() {
      return lastestMsg_ == null ? org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance() : lastestMsg_;
    }

    public static final int ONEPAGEMSGS_FIELD_NUMBER = 5;
    private java.util.List<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope> onePageMsgs_;
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    public java.util.List<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope> getOnePageMsgsList() {
      return onePageMsgs_;
    }
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    public java.util.List<? extends org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> 
        getOnePageMsgsOrBuilderList() {
      return onePageMsgs_;
    }
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    public int getOnePageMsgsCount() {
      return onePageMsgs_.size();
    }
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope getOnePageMsgs(int index) {
      return onePageMsgs_.get(index);
    }
    /**
     * <pre>
     *null
     * </pre>
     *
     * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
     */
    public org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder getOnePageMsgsOrBuilder(
        int index) {
      return onePageMsgs_.get(index);
    }

    public static final int MAXOUTGOINGNSID_FIELD_NUMBER = 6;
    private long maxOutgoingNsId_;
    /**
     * <pre>
     *自己发送的可见消息最大NsId，用于计算未读数
     * </pre>
     *
     * <code>optional uint64 maxOutgoingNsId = 6;</code>
     */
    public boolean hasMaxOutgoingNsId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *自己发送的可见消息最大NsId，用于计算未读数
     * </pre>
     *
     * <code>optional uint64 maxOutgoingNsId = 6;</code>
     */
    public long getMaxOutgoingNsId() {
      return maxOutgoingNsId_;
    }

    public static final int OLDESTMSGSID_FIELD_NUMBER = 7;
    private long oldestMsgSId_;
    /**
     * <pre>
     *可拉取最老的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgSId = 7;</code>
     */
    public boolean hasOldestMsgSId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *可拉取最老的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgSId = 7;</code>
     */
    public long getOldestMsgSId() {
      return oldestMsgSId_;
    }

    public static final int OLDESTMSGNSID_FIELD_NUMBER = 8;
    private long oldestMsgNsId_;
    /**
     * <pre>
     *可拉取最老的消息notifySequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgNsId = 8;</code>
     */
    public boolean hasOldestMsgNsId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *可拉取最老的消息notifySequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 oldestMsgNsId = 8;</code>
     */
    public long getOldestMsgNsId() {
      return oldestMsgNsId_;
    }

    public static final int LASTESTMSGSID_FIELD_NUMBER = 9;
    private long lastestMsgSId_;
    /**
     * <pre>
     *可拉取最新的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 lastestMsgSId = 9;</code>
     */
    public boolean hasLastestMsgSId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *可拉取最新的消息sequenceId，用于拉取消息
     * </pre>
     *
     * <code>optional uint64 lastestMsgSId = 9;</code>
     */
    public long getLastestMsgSId() {
      return lastestMsgSId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getConversationId());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getReadPosition());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, unreadCorrection_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getLastestMsg());
      }
      for (int i = 0; i < onePageMsgs_.size(); i++) {
        output.writeMessage(5, onePageMsgs_.get(i));
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(6, maxOutgoingNsId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt64(7, oldestMsgSId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt64(8, oldestMsgNsId_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt64(9, lastestMsgSId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConversationId());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReadPosition());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, unreadCorrection_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLastestMsg());
      }
      for (int i = 0; i < onePageMsgs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, onePageMsgs_.get(i));
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, maxOutgoingNsId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, oldestMsgSId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, oldestMsgNsId_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, lastestMsgSId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo)) {
        return super.equals(obj);
      }
      org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo other = (org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo) obj;

      if (hasConversationId() != other.hasConversationId()) return false;
      if (hasConversationId()) {
        if (!getConversationId()
            .equals(other.getConversationId())) return false;
      }
      if (hasReadPosition() != other.hasReadPosition()) return false;
      if (hasReadPosition()) {
        if (!getReadPosition()
            .equals(other.getReadPosition())) return false;
      }
      if (hasUnreadCorrection() != other.hasUnreadCorrection()) return false;
      if (hasUnreadCorrection()) {
        if (getUnreadCorrection()
            != other.getUnreadCorrection()) return false;
      }
      if (hasLastestMsg() != other.hasLastestMsg()) return false;
      if (hasLastestMsg()) {
        if (!getLastestMsg()
            .equals(other.getLastestMsg())) return false;
      }
      if (!getOnePageMsgsList()
          .equals(other.getOnePageMsgsList())) return false;
      if (hasMaxOutgoingNsId() != other.hasMaxOutgoingNsId()) return false;
      if (hasMaxOutgoingNsId()) {
        if (getMaxOutgoingNsId()
            != other.getMaxOutgoingNsId()) return false;
      }
      if (hasOldestMsgSId() != other.hasOldestMsgSId()) return false;
      if (hasOldestMsgSId()) {
        if (getOldestMsgSId()
            != other.getOldestMsgSId()) return false;
      }
      if (hasOldestMsgNsId() != other.hasOldestMsgNsId()) return false;
      if (hasOldestMsgNsId()) {
        if (getOldestMsgNsId()
            != other.getOldestMsgNsId()) return false;
      }
      if (hasLastestMsgSId() != other.hasLastestMsgSId()) return false;
      if (hasLastestMsgSId()) {
        if (getLastestMsgSId()
            != other.getLastestMsgSId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConversationId()) {
        hash = (37 * hash) + CONVERSATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getConversationId().hashCode();
      }
      if (hasReadPosition()) {
        hash = (37 * hash) + READPOSITION_FIELD_NUMBER;
        hash = (53 * hash) + getReadPosition().hashCode();
      }
      if (hasUnreadCorrection()) {
        hash = (37 * hash) + UNREADCORRECTION_FIELD_NUMBER;
        hash = (53 * hash) + getUnreadCorrection();
      }
      if (hasLastestMsg()) {
        hash = (37 * hash) + LASTESTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getLastestMsg().hashCode();
      }
      if (getOnePageMsgsCount() > 0) {
        hash = (37 * hash) + ONEPAGEMSGS_FIELD_NUMBER;
        hash = (53 * hash) + getOnePageMsgsList().hashCode();
      }
      if (hasMaxOutgoingNsId()) {
        hash = (37 * hash) + MAXOUTGOINGNSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMaxOutgoingNsId());
      }
      if (hasOldestMsgSId()) {
        hash = (37 * hash) + OLDESTMSGSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOldestMsgSId());
      }
      if (hasOldestMsgNsId()) {
        hash = (37 * hash) + OLDESTMSGNSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOldestMsgNsId());
      }
      if (hasLastestMsgSId()) {
        hash = (37 * hash) + LASTESTMSGSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastestMsgSId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code textsecure.ConversationMsgInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:textsecure.ConversationMsgInfo)
        org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.internal_static_textsecure_ConversationMsgInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.internal_static_textsecure_ConversationMsgInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.class, org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.Builder.class);
      }

      // Construct using org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConversationIdFieldBuilder();
          getReadPositionFieldBuilder();
          getLastestMsgFieldBuilder();
          getOnePageMsgsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (conversationIdBuilder_ == null) {
          conversationId_ = null;
        } else {
          conversationIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (readPositionBuilder_ == null) {
          readPosition_ = null;
        } else {
          readPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        unreadCorrection_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (lastestMsgBuilder_ == null) {
          lastestMsg_ = null;
        } else {
          lastestMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (onePageMsgsBuilder_ == null) {
          onePageMsgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          onePageMsgsBuilder_.clear();
        }
        maxOutgoingNsId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        oldestMsgSId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        oldestMsgNsId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastestMsgSId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.internal_static_textsecure_ConversationMsgInfo_descriptor;
      }

      @java.lang.Override
      public org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo getDefaultInstanceForType() {
        return org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo build() {
        org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo buildPartial() {
        org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo result = new org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (conversationIdBuilder_ == null) {
            result.conversationId_ = conversationId_;
          } else {
            result.conversationId_ = conversationIdBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (readPositionBuilder_ == null) {
            result.readPosition_ = readPosition_;
          } else {
            result.readPosition_ = readPositionBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.unreadCorrection_ = unreadCorrection_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (lastestMsgBuilder_ == null) {
            result.lastestMsg_ = lastestMsg_;
          } else {
            result.lastestMsg_ = lastestMsgBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        if (onePageMsgsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            onePageMsgs_ = java.util.Collections.unmodifiableList(onePageMsgs_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.onePageMsgs_ = onePageMsgs_;
        } else {
          result.onePageMsgs_ = onePageMsgsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.maxOutgoingNsId_ = maxOutgoingNsId_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.oldestMsgSId_ = oldestMsgSId_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.oldestMsgNsId_ = oldestMsgNsId_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.lastestMsgSId_ = lastestMsgSId_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo) {
          return mergeFrom((org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo other) {
        if (other == org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo.getDefaultInstance()) return this;
        if (other.hasConversationId()) {
          mergeConversationId(other.getConversationId());
        }
        if (other.hasReadPosition()) {
          mergeReadPosition(other.getReadPosition());
        }
        if (other.hasUnreadCorrection()) {
          setUnreadCorrection(other.getUnreadCorrection());
        }
        if (other.hasLastestMsg()) {
          mergeLastestMsg(other.getLastestMsg());
        }
        if (onePageMsgsBuilder_ == null) {
          if (!other.onePageMsgs_.isEmpty()) {
            if (onePageMsgs_.isEmpty()) {
              onePageMsgs_ = other.onePageMsgs_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureOnePageMsgsIsMutable();
              onePageMsgs_.addAll(other.onePageMsgs_);
            }
            onChanged();
          }
        } else {
          if (!other.onePageMsgs_.isEmpty()) {
            if (onePageMsgsBuilder_.isEmpty()) {
              onePageMsgsBuilder_.dispose();
              onePageMsgsBuilder_ = null;
              onePageMsgs_ = other.onePageMsgs_;
              bitField0_ = (bitField0_ & ~0x00000010);
              onePageMsgsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOnePageMsgsFieldBuilder() : null;
            } else {
              onePageMsgsBuilder_.addAllMessages(other.onePageMsgs_);
            }
          }
        }
        if (other.hasMaxOutgoingNsId()) {
          setMaxOutgoingNsId(other.getMaxOutgoingNsId());
        }
        if (other.hasOldestMsgSId()) {
          setOldestMsgSId(other.getOldestMsgSId());
        }
        if (other.hasOldestMsgNsId()) {
          setOldestMsgNsId(other.getOldestMsgNsId());
        }
        if (other.hasLastestMsgSId()) {
          setLastestMsgSId(other.getLastestMsgSId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId conversationId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.Builder, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationIdOrBuilder> conversationIdBuilder_;
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public boolean hasConversationId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId getConversationId() {
        if (conversationIdBuilder_ == null) {
          return conversationId_ == null ? org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.getDefaultInstance() : conversationId_;
        } else {
          return conversationIdBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public Builder setConversationId(org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId value) {
        if (conversationIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          conversationId_ = value;
          onChanged();
        } else {
          conversationIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public Builder setConversationId(
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.Builder builderForValue) {
        if (conversationIdBuilder_ == null) {
          conversationId_ = builderForValue.build();
          onChanged();
        } else {
          conversationIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public Builder mergeConversationId(org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId value) {
        if (conversationIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              conversationId_ != null &&
              conversationId_ != org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.getDefaultInstance()) {
            conversationId_ =
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.newBuilder(conversationId_).mergeFrom(value).buildPartial();
          } else {
            conversationId_ = value;
          }
          onChanged();
        } else {
          conversationIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public Builder clearConversationId() {
        if (conversationIdBuilder_ == null) {
          conversationId_ = null;
          onChanged();
        } else {
          conversationIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.Builder getConversationIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getConversationIdFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationIdOrBuilder getConversationIdOrBuilder() {
        if (conversationIdBuilder_ != null) {
          return conversationIdBuilder_.getMessageOrBuilder();
        } else {
          return conversationId_ == null ?
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.getDefaultInstance() : conversationId_;
        }
      }
      /**
       * <pre>
       *会话信息
       * </pre>
       *
       * <code>optional .textsecure.ConversationId conversationId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.Builder, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationIdOrBuilder> 
          getConversationIdFieldBuilder() {
        if (conversationIdBuilder_ == null) {
          conversationIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationId.Builder, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ConversationIdOrBuilder>(
                  getConversationId(),
                  getParentForChildren(),
                  isClean());
          conversationId_ = null;
        }
        return conversationIdBuilder_;
      }

      private org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition readPosition_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.Builder, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPositionOrBuilder> readPositionBuilder_;
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public boolean hasReadPosition() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition getReadPosition() {
        if (readPositionBuilder_ == null) {
          return readPosition_ == null ? org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.getDefaultInstance() : readPosition_;
        } else {
          return readPositionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public Builder setReadPosition(org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition value) {
        if (readPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          readPosition_ = value;
          onChanged();
        } else {
          readPositionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public Builder setReadPosition(
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.Builder builderForValue) {
        if (readPositionBuilder_ == null) {
          readPosition_ = builderForValue.build();
          onChanged();
        } else {
          readPositionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public Builder mergeReadPosition(org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition value) {
        if (readPositionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              readPosition_ != null &&
              readPosition_ != org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.getDefaultInstance()) {
            readPosition_ =
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.newBuilder(readPosition_).mergeFrom(value).buildPartial();
          } else {
            readPosition_ = value;
          }
          onChanged();
        } else {
          readPositionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public Builder clearReadPosition() {
        if (readPositionBuilder_ == null) {
          readPosition_ = null;
          onChanged();
        } else {
          readPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.Builder getReadPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReadPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      public org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPositionOrBuilder getReadPositionOrBuilder() {
        if (readPositionBuilder_ != null) {
          return readPositionBuilder_.getMessageOrBuilder();
        } else {
          return readPosition_ == null ?
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.getDefaultInstance() : readPosition_;
        }
      }
      /**
       * <pre>
       *已读位置，用于计算未读数
       * </pre>
       *
       * <code>optional .textsecure.ReadPosition readPosition = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.Builder, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPositionOrBuilder> 
          getReadPositionFieldBuilder() {
        if (readPositionBuilder_ == null) {
          readPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPosition.Builder, org.whispersystems.textsecuregcm.entities.ConversationPreviews.ReadPositionOrBuilder>(
                  getReadPosition(),
                  getParentForChildren(),
                  isClean());
          readPosition_ = null;
        }
        return readPositionBuilder_;
      }

      private int unreadCorrection_ ;
      /**
       * <pre>
       *已读矫正值，用于计算未读数
       * </pre>
       *
       * <code>optional uint32 unreadCorrection = 3;</code>
       */
      public boolean hasUnreadCorrection() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *已读矫正值，用于计算未读数
       * </pre>
       *
       * <code>optional uint32 unreadCorrection = 3;</code>
       */
      public int getUnreadCorrection() {
        return unreadCorrection_;
      }
      /**
       * <pre>
       *已读矫正值，用于计算未读数
       * </pre>
       *
       * <code>optional uint32 unreadCorrection = 3;</code>
       */
      public Builder setUnreadCorrection(int value) {
        bitField0_ |= 0x00000004;
        unreadCorrection_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读矫正值，用于计算未读数
       * </pre>
       *
       * <code>optional uint32 unreadCorrection = 3;</code>
       */
      public Builder clearUnreadCorrection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        unreadCorrection_ = 0;
        onChanged();
        return this;
      }

      private org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope lastestMsg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder, org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> lastestMsgBuilder_;
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public boolean hasLastestMsg() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope getLastestMsg() {
        if (lastestMsgBuilder_ == null) {
          return lastestMsg_ == null ? org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance() : lastestMsg_;
        } else {
          return lastestMsgBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public Builder setLastestMsg(org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope value) {
        if (lastestMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastestMsg_ = value;
          onChanged();
        } else {
          lastestMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public Builder setLastestMsg(
          org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder builderForValue) {
        if (lastestMsgBuilder_ == null) {
          lastestMsg_ = builderForValue.build();
          onChanged();
        } else {
          lastestMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public Builder mergeLastestMsg(org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope value) {
        if (lastestMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              lastestMsg_ != null &&
              lastestMsg_ != org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance()) {
            lastestMsg_ =
              org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.newBuilder(lastestMsg_).mergeFrom(value).buildPartial();
          } else {
            lastestMsg_ = value;
          }
          onChanged();
        } else {
          lastestMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public Builder clearLastestMsg() {
        if (lastestMsgBuilder_ == null) {
          lastestMsg_ = null;
          onChanged();
        } else {
          lastestMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder getLastestMsgBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getLastestMsgFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder getLastestMsgOrBuilder() {
        if (lastestMsgBuilder_ != null) {
          return lastestMsgBuilder_.getMessageOrBuilder();
        } else {
          return lastestMsg_ == null ?
              org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance() : lastestMsg_;
        }
      }
      /**
       * <pre>
       *最新的一条可见消息，用于消息预览
       * </pre>
       *
       * <code>optional .textsecure.Envelope lastestMsg = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder, org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> 
          getLastestMsgFieldBuilder() {
        if (lastestMsgBuilder_ == null) {
          lastestMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder, org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder>(
                  getLastestMsg(),
                  getParentForChildren(),
                  isClean());
          lastestMsg_ = null;
        }
        return lastestMsgBuilder_;
      }

      private java.util.List<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope> onePageMsgs_ =
        java.util.Collections.emptyList();
      private void ensureOnePageMsgsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          onePageMsgs_ = new java.util.ArrayList<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope>(onePageMsgs_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder, org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> onePageMsgsBuilder_;

      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public java.util.List<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope> getOnePageMsgsList() {
        if (onePageMsgsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(onePageMsgs_);
        } else {
          return onePageMsgsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public int getOnePageMsgsCount() {
        if (onePageMsgsBuilder_ == null) {
          return onePageMsgs_.size();
        } else {
          return onePageMsgsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope getOnePageMsgs(int index) {
        if (onePageMsgsBuilder_ == null) {
          return onePageMsgs_.get(index);
        } else {
          return onePageMsgsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder setOnePageMsgs(
          int index, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope value) {
        if (onePageMsgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.set(index, value);
          onChanged();
        } else {
          onePageMsgsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder setOnePageMsgs(
          int index, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder builderForValue) {
        if (onePageMsgsBuilder_ == null) {
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.set(index, builderForValue.build());
          onChanged();
        } else {
          onePageMsgsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder addOnePageMsgs(org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope value) {
        if (onePageMsgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.add(value);
          onChanged();
        } else {
          onePageMsgsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder addOnePageMsgs(
          int index, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope value) {
        if (onePageMsgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.add(index, value);
          onChanged();
        } else {
          onePageMsgsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder addOnePageMsgs(
          org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder builderForValue) {
        if (onePageMsgsBuilder_ == null) {
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.add(builderForValue.build());
          onChanged();
        } else {
          onePageMsgsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder addOnePageMsgs(
          int index, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder builderForValue) {
        if (onePageMsgsBuilder_ == null) {
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.add(index, builderForValue.build());
          onChanged();
        } else {
          onePageMsgsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder addAllOnePageMsgs(
          java.lang.Iterable<? extends org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope> values) {
        if (onePageMsgsBuilder_ == null) {
          ensureOnePageMsgsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, onePageMsgs_);
          onChanged();
        } else {
          onePageMsgsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder clearOnePageMsgs() {
        if (onePageMsgsBuilder_ == null) {
          onePageMsgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          onePageMsgsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public Builder removeOnePageMsgs(int index) {
        if (onePageMsgsBuilder_ == null) {
          ensureOnePageMsgsIsMutable();
          onePageMsgs_.remove(index);
          onChanged();
        } else {
          onePageMsgsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder getOnePageMsgsBuilder(
          int index) {
        return getOnePageMsgsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder getOnePageMsgsOrBuilder(
          int index) {
        if (onePageMsgsBuilder_ == null) {
          return onePageMsgs_.get(index);  } else {
          return onePageMsgsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public java.util.List<? extends org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> 
           getOnePageMsgsOrBuilderList() {
        if (onePageMsgsBuilder_ != null) {
          return onePageMsgsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(onePageMsgs_);
        }
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder addOnePageMsgsBuilder() {
        return getOnePageMsgsFieldBuilder().addBuilder(
            org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance());
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder addOnePageMsgsBuilder(
          int index) {
        return getOnePageMsgsFieldBuilder().addBuilder(
            index, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.getDefaultInstance());
      }
      /**
       * <pre>
       *null
       * </pre>
       *
       * <code>repeated .textsecure.Envelope onePageMsgs = 5;</code>
       */
      public java.util.List<org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder> 
           getOnePageMsgsBuilderList() {
        return getOnePageMsgsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder, org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder> 
          getOnePageMsgsFieldBuilder() {
        if (onePageMsgsBuilder_ == null) {
          onePageMsgsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope, org.whispersystems.textsecuregcm.entities.MessageProtos.Envelope.Builder, org.whispersystems.textsecuregcm.entities.MessageProtos.EnvelopeOrBuilder>(
                  onePageMsgs_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          onePageMsgs_ = null;
        }
        return onePageMsgsBuilder_;
      }

      private long maxOutgoingNsId_ ;
      /**
       * <pre>
       *自己发送的可见消息最大NsId，用于计算未读数
       * </pre>
       *
       * <code>optional uint64 maxOutgoingNsId = 6;</code>
       */
      public boolean hasMaxOutgoingNsId() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *自己发送的可见消息最大NsId，用于计算未读数
       * </pre>
       *
       * <code>optional uint64 maxOutgoingNsId = 6;</code>
       */
      public long getMaxOutgoingNsId() {
        return maxOutgoingNsId_;
      }
      /**
       * <pre>
       *自己发送的可见消息最大NsId，用于计算未读数
       * </pre>
       *
       * <code>optional uint64 maxOutgoingNsId = 6;</code>
       */
      public Builder setMaxOutgoingNsId(long value) {
        bitField0_ |= 0x00000020;
        maxOutgoingNsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自己发送的可见消息最大NsId，用于计算未读数
       * </pre>
       *
       * <code>optional uint64 maxOutgoingNsId = 6;</code>
       */
      public Builder clearMaxOutgoingNsId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        maxOutgoingNsId_ = 0L;
        onChanged();
        return this;
      }

      private long oldestMsgSId_ ;
      /**
       * <pre>
       *可拉取最老的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgSId = 7;</code>
       */
      public boolean hasOldestMsgSId() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *可拉取最老的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgSId = 7;</code>
       */
      public long getOldestMsgSId() {
        return oldestMsgSId_;
      }
      /**
       * <pre>
       *可拉取最老的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgSId = 7;</code>
       */
      public Builder setOldestMsgSId(long value) {
        bitField0_ |= 0x00000040;
        oldestMsgSId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *可拉取最老的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgSId = 7;</code>
       */
      public Builder clearOldestMsgSId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        oldestMsgSId_ = 0L;
        onChanged();
        return this;
      }

      private long oldestMsgNsId_ ;
      /**
       * <pre>
       *可拉取最老的消息notifySequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgNsId = 8;</code>
       */
      public boolean hasOldestMsgNsId() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *可拉取最老的消息notifySequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgNsId = 8;</code>
       */
      public long getOldestMsgNsId() {
        return oldestMsgNsId_;
      }
      /**
       * <pre>
       *可拉取最老的消息notifySequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgNsId = 8;</code>
       */
      public Builder setOldestMsgNsId(long value) {
        bitField0_ |= 0x00000080;
        oldestMsgNsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *可拉取最老的消息notifySequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 oldestMsgNsId = 8;</code>
       */
      public Builder clearOldestMsgNsId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        oldestMsgNsId_ = 0L;
        onChanged();
        return this;
      }

      private long lastestMsgSId_ ;
      /**
       * <pre>
       *可拉取最新的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 lastestMsgSId = 9;</code>
       */
      public boolean hasLastestMsgSId() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       *可拉取最新的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 lastestMsgSId = 9;</code>
       */
      public long getLastestMsgSId() {
        return lastestMsgSId_;
      }
      /**
       * <pre>
       *可拉取最新的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 lastestMsgSId = 9;</code>
       */
      public Builder setLastestMsgSId(long value) {
        bitField0_ |= 0x00000100;
        lastestMsgSId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *可拉取最新的消息sequenceId，用于拉取消息
       * </pre>
       *
       * <code>optional uint64 lastestMsgSId = 9;</code>
       */
      public Builder clearLastestMsgSId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastestMsgSId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:textsecure.ConversationMsgInfo)
    }

    // @@protoc_insertion_point(class_scope:textsecure.ConversationMsgInfo)
    private static final org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo();
    }

    public static org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ConversationMsgInfo>
        PARSER = new com.google.protobuf.AbstractParser<ConversationMsgInfo>() {
      @java.lang.Override
      public ConversationMsgInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConversationMsgInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConversationMsgInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConversationMsgInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.entities.ConversationMsgInfos.ConversationMsgInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_textsecure_ConversationMsgInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_textsecure_ConversationMsgInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ConversationMsgInfo.proto\022\ntextsecure\032" +
      "\020TextSecure.proto\032\031ConversationPreview.p" +
      "roto\"\305\002\n\023ConversationMsgInfo\0222\n\016conversa" +
      "tionId\030\001 \001(\0132\032.textsecure.ConversationId" +
      "\022.\n\014readPosition\030\002 \001(\0132\030.textsecure.Read" +
      "Position\022\030\n\020unreadCorrection\030\003 \001(\r\022(\n\nla" +
      "stestMsg\030\004 \001(\0132\024.textsecure.Envelope\022)\n\013" +
      "onePageMsgs\030\005 \003(\0132\024.textsecure.Envelope\022" +
      "\027\n\017maxOutgoingNsId\030\006 \001(\004\022\024\n\014oldestMsgSId" +
      "\030\007 \001(\004\022\025\n\roldestMsgNsId\030\010 \001(\004\022\025\n\rlastest" +
      "MsgSId\030\t \001(\004BA\n)org.whispersystems.texts" +
      "ecuregcm.entitiesB\024ConversationMsgInfos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.whispersystems.textsecuregcm.entities.MessageProtos.getDescriptor(),
          org.whispersystems.textsecuregcm.entities.ConversationPreviews.getDescriptor(),
        });
    internal_static_textsecure_ConversationMsgInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_textsecure_ConversationMsgInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_textsecure_ConversationMsgInfo_descriptor,
        new java.lang.String[] { "ConversationId", "ReadPosition", "UnreadCorrection", "LastestMsg", "OnePageMsgs", "MaxOutgoingNsId", "OldestMsgSId", "OldestMsgNsId", "LastestMsgSId", });
    org.whispersystems.textsecuregcm.entities.MessageProtos.getDescriptor();
    org.whispersystems.textsecuregcm.entities.ConversationPreviews.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
