// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientService.proto

package org.whispersystems.textsecuregcm.internal.clients;

public interface ClientVersionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientVersionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ClientVersionResponse.ClientVersionCntWithOS osVersions = 1;</code>
   */
  java.util.List<org.whispersystems.textsecuregcm.internal.clients.ClientVersionResponse.ClientVersionCntWithOS> 
      getOsVersionsList();
  /**
   * <code>repeated .ClientVersionResponse.ClientVersionCntWithOS osVersions = 1;</code>
   */
  org.whispersystems.textsecuregcm.internal.clients.ClientVersionResponse.ClientVersionCntWithOS getOsVersions(int index);
  /**
   * <code>repeated .ClientVersionResponse.ClientVersionCntWithOS osVersions = 1;</code>
   */
  int getOsVersionsCount();
  /**
   * <code>repeated .ClientVersionResponse.ClientVersionCntWithOS osVersions = 1;</code>
   */
  java.util.List<? extends org.whispersystems.textsecuregcm.internal.clients.ClientVersionResponse.ClientVersionCntWithOSOrBuilder> 
      getOsVersionsOrBuilderList();
  /**
   * <code>repeated .ClientVersionResponse.ClientVersionCntWithOS osVersions = 1;</code>
   */
  org.whispersystems.textsecuregcm.internal.clients.ClientVersionResponse.ClientVersionCntWithOSOrBuilder getOsVersionsOrBuilder(
      int index);
}
