// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

/**
 * Protobuf type {@code AccountQueryInfo}
 */
public  final class AccountQueryInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AccountQueryInfo)
    AccountQueryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountQueryInfo.newBuilder() to construct.
  private AccountQueryInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountQueryInfo() {
    email_ = "";
    wuid_ = "";
    nickname_ = "";
    reason_ = "";
    signature_ = "";
    fullName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AccountQueryInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountQueryInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            email_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            wuid_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            nickname_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            reason_ = bs;
            break;
          }
          case 42: {
            org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) != 0)) {
              subBuilder = avatarInfo_.toBuilder();
            }
            avatarInfo_ = input.readMessage(org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(avatarInfo_);
              avatarInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            signature_ = bs;
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            fullName_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_AccountQueryInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_AccountQueryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.class, org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.Builder.class);
  }

  private int bitField0_;
  public static final int EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object email_;
  /**
   * <code>optional string email = 1;</code>
   */
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string email = 1;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        email_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string email = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object wuid_;
  /**
   * <code>optional string wuid = 2;</code>
   */
  public boolean hasWuid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string wuid = 2;</code>
   */
  public java.lang.String getWuid() {
    java.lang.Object ref = wuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        wuid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string wuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWuidBytes() {
    java.lang.Object ref = wuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object nickname_;
  /**
   * <code>optional string nickname = 3;</code>
   */
  public boolean hasNickname() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string nickname = 3;</code>
   */
  public java.lang.String getNickname() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nickname_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string nickname = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNicknameBytes() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REASON_FIELD_NUMBER = 4;
  private volatile java.lang.Object reason_;
  /**
   * <code>optional string reason = 4;</code>
   */
  public boolean hasReason() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string reason = 4;</code>
   */
  public java.lang.String getReason() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        reason_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string reason = 4;</code>
   */
  public com.google.protobuf.ByteString
      getReasonBytes() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATARINFO_FIELD_NUMBER = 5;
  private org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo avatarInfo_;
  /**
   * <code>optional .AvatarInfo avatarInfo = 5;</code>
   */
  public boolean hasAvatarInfo() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .AvatarInfo avatarInfo = 5;</code>
   */
  public org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo getAvatarInfo() {
    return avatarInfo_ == null ? org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.getDefaultInstance() : avatarInfo_;
  }
  /**
   * <code>optional .AvatarInfo avatarInfo = 5;</code>
   */
  public org.whispersystems.textsecuregcm.internal.accounts.AvatarInfoOrBuilder getAvatarInfoOrBuilder() {
    return avatarInfo_ == null ? org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.getDefaultInstance() : avatarInfo_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 6;
  private volatile java.lang.Object signature_;
  /**
   * <code>optional string signature = 6;</code>
   */
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string signature = 6;</code>
   */
  public java.lang.String getSignature() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        signature_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string signature = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSignatureBytes() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULLNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object fullName_;
  /**
   * <code>optional string fullName = 7;</code>
   */
  public boolean hasFullName() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string fullName = 7;</code>
   */
  public java.lang.String getFullName() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        fullName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string fullName = 7;</code>
   */
  public com.google.protobuf.ByteString
      getFullNameBytes() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasAvatarInfo()) {
      if (!getAvatarInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, wuid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickname_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, reason_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getAvatarInfo());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, signature_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fullName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, wuid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickname_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, reason_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAvatarInfo());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, signature_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, fullName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo other = (org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo) obj;

    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (hasWuid() != other.hasWuid()) return false;
    if (hasWuid()) {
      if (!getWuid()
          .equals(other.getWuid())) return false;
    }
    if (hasNickname() != other.hasNickname()) return false;
    if (hasNickname()) {
      if (!getNickname()
          .equals(other.getNickname())) return false;
    }
    if (hasReason() != other.hasReason()) return false;
    if (hasReason()) {
      if (!getReason()
          .equals(other.getReason())) return false;
    }
    if (hasAvatarInfo() != other.hasAvatarInfo()) return false;
    if (hasAvatarInfo()) {
      if (!getAvatarInfo()
          .equals(other.getAvatarInfo())) return false;
    }
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (hasFullName() != other.hasFullName()) return false;
    if (hasFullName()) {
      if (!getFullName()
          .equals(other.getFullName())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasWuid()) {
      hash = (37 * hash) + WUID_FIELD_NUMBER;
      hash = (53 * hash) + getWuid().hashCode();
    }
    if (hasNickname()) {
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
    }
    if (hasReason()) {
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
    }
    if (hasAvatarInfo()) {
      hash = (37 * hash) + AVATARINFO_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarInfo().hashCode();
    }
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    if (hasFullName()) {
      hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullName().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AccountQueryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AccountQueryInfo)
      org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_AccountQueryInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_AccountQueryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.class, org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAvatarInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      email_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      wuid_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      nickname_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      reason_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      if (avatarInfoBuilder_ == null) {
        avatarInfo_ = null;
      } else {
        avatarInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      signature_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      fullName_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_AccountQueryInfo_descriptor;
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo build() {
      org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo buildPartial() {
      org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo result = new org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.email_ = email_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.wuid_ = wuid_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.nickname_ = nickname_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.reason_ = reason_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (avatarInfoBuilder_ == null) {
          result.avatarInfo_ = avatarInfo_;
        } else {
          result.avatarInfo_ = avatarInfoBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.signature_ = signature_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.fullName_ = fullName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo) {
        return mergeFrom((org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo other) {
      if (other == org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo.getDefaultInstance()) return this;
      if (other.hasEmail()) {
        bitField0_ |= 0x00000001;
        email_ = other.email_;
        onChanged();
      }
      if (other.hasWuid()) {
        bitField0_ |= 0x00000002;
        wuid_ = other.wuid_;
        onChanged();
      }
      if (other.hasNickname()) {
        bitField0_ |= 0x00000004;
        nickname_ = other.nickname_;
        onChanged();
      }
      if (other.hasReason()) {
        bitField0_ |= 0x00000008;
        reason_ = other.reason_;
        onChanged();
      }
      if (other.hasAvatarInfo()) {
        mergeAvatarInfo(other.getAvatarInfo());
      }
      if (other.hasSignature()) {
        bitField0_ |= 0x00000020;
        signature_ = other.signature_;
        onChanged();
      }
      if (other.hasFullName()) {
        bitField0_ |= 0x00000040;
        fullName_ = other.fullName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (hasAvatarInfo()) {
        if (!getAvatarInfo().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 1;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000001);
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wuid_ = "";
    /**
     * <code>optional string wuid = 2;</code>
     */
    public boolean hasWuid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string wuid = 2;</code>
     */
    public java.lang.String getWuid() {
      java.lang.Object ref = wuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wuid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string wuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWuidBytes() {
      java.lang.Object ref = wuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string wuid = 2;</code>
     */
    public Builder setWuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      wuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string wuid = 2;</code>
     */
    public Builder clearWuid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      wuid_ = getDefaultInstance().getWuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string wuid = 2;</code>
     */
    public Builder setWuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      wuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nickname_ = "";
    /**
     * <code>optional string nickname = 3;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public Builder setNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      nickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public Builder clearNickname() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nickname_ = getDefaultInstance().getNickname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public Builder setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      nickname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object reason_ = "";
    /**
     * <code>optional string reason = 4;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string reason = 4;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reason_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string reason = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reason = 4;</code>
     */
    public Builder setReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      reason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reason = 4;</code>
     */
    public Builder clearReason() {
      bitField0_ = (bitField0_ & ~0x00000008);
      reason_ = getDefaultInstance().getReason();
      onChanged();
      return this;
    }
    /**
     * <code>optional string reason = 4;</code>
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      reason_ = value;
      onChanged();
      return this;
    }

    private org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo avatarInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo, org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.Builder, org.whispersystems.textsecuregcm.internal.accounts.AvatarInfoOrBuilder> avatarInfoBuilder_;
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public boolean hasAvatarInfo() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo getAvatarInfo() {
      if (avatarInfoBuilder_ == null) {
        return avatarInfo_ == null ? org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.getDefaultInstance() : avatarInfo_;
      } else {
        return avatarInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public Builder setAvatarInfo(org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo value) {
      if (avatarInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        avatarInfo_ = value;
        onChanged();
      } else {
        avatarInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public Builder setAvatarInfo(
        org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.Builder builderForValue) {
      if (avatarInfoBuilder_ == null) {
        avatarInfo_ = builderForValue.build();
        onChanged();
      } else {
        avatarInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public Builder mergeAvatarInfo(org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo value) {
      if (avatarInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            avatarInfo_ != null &&
            avatarInfo_ != org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.getDefaultInstance()) {
          avatarInfo_ =
            org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.newBuilder(avatarInfo_).mergeFrom(value).buildPartial();
        } else {
          avatarInfo_ = value;
        }
        onChanged();
      } else {
        avatarInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public Builder clearAvatarInfo() {
      if (avatarInfoBuilder_ == null) {
        avatarInfo_ = null;
        onChanged();
      } else {
        avatarInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.Builder getAvatarInfoBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getAvatarInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    public org.whispersystems.textsecuregcm.internal.accounts.AvatarInfoOrBuilder getAvatarInfoOrBuilder() {
      if (avatarInfoBuilder_ != null) {
        return avatarInfoBuilder_.getMessageOrBuilder();
      } else {
        return avatarInfo_ == null ?
            org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.getDefaultInstance() : avatarInfo_;
      }
    }
    /**
     * <code>optional .AvatarInfo avatarInfo = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo, org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.Builder, org.whispersystems.textsecuregcm.internal.accounts.AvatarInfoOrBuilder> 
        getAvatarInfoFieldBuilder() {
      if (avatarInfoBuilder_ == null) {
        avatarInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo, org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo.Builder, org.whispersystems.textsecuregcm.internal.accounts.AvatarInfoOrBuilder>(
                getAvatarInfo(),
                getParentForChildren(),
                isClean());
        avatarInfo_ = null;
      }
      return avatarInfoBuilder_;
    }

    private java.lang.Object signature_ = "";
    /**
     * <code>optional string signature = 6;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string signature = 6;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string signature = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string signature = 6;</code>
     */
    public Builder setSignature(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string signature = 6;</code>
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000020);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    /**
     * <code>optional string signature = 6;</code>
     */
    public Builder setSignatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      signature_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fullName_ = "";
    /**
     * <code>optional string fullName = 7;</code>
     */
    public boolean hasFullName() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string fullName = 7;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string fullName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string fullName = 7;</code>
     */
    public Builder setFullName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      fullName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string fullName = 7;</code>
     */
    public Builder clearFullName() {
      bitField0_ = (bitField0_ & ~0x00000040);
      fullName_ = getDefaultInstance().getFullName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string fullName = 7;</code>
     */
    public Builder setFullNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      fullName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AccountQueryInfo)
  }

  // @@protoc_insertion_point(class_scope:AccountQueryInfo)
  private static final org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo();
  }

  public static org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AccountQueryInfo>
      PARSER = new com.google.protobuf.AbstractParser<AccountQueryInfo>() {
    @java.lang.Override
    public AccountQueryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountQueryInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountQueryInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountQueryInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.whispersystems.textsecuregcm.internal.accounts.AccountQueryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

