// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

public interface AccountQueryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountQueryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string email = 1;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string wuid = 2;</code>
   */
  boolean hasWuid();
  /**
   * <code>optional string wuid = 2;</code>
   */
  java.lang.String getWuid();
  /**
   * <code>optional string wuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getWuidBytes();

  /**
   * <code>optional string nickname = 3;</code>
   */
  boolean hasNickname();
  /**
   * <code>optional string nickname = 3;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>optional string nickname = 3;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>optional string reason = 4;</code>
   */
  boolean hasReason();
  /**
   * <code>optional string reason = 4;</code>
   */
  java.lang.String getReason();
  /**
   * <code>optional string reason = 4;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>optional .AvatarInfo avatarInfo = 5;</code>
   */
  boolean hasAvatarInfo();
  /**
   * <code>optional .AvatarInfo avatarInfo = 5;</code>
   */
  org.whispersystems.textsecuregcm.internal.accounts.AvatarInfo getAvatarInfo();
  /**
   * <code>optional .AvatarInfo avatarInfo = 5;</code>
   */
  org.whispersystems.textsecuregcm.internal.accounts.AvatarInfoOrBuilder getAvatarInfoOrBuilder();

  /**
   * <code>optional string signature = 6;</code>
   */
  boolean hasSignature();
  /**
   * <code>optional string signature = 6;</code>
   */
  java.lang.String getSignature();
  /**
   * <code>optional string signature = 6;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <code>optional string fullName = 7;</code>
   */
  boolean hasFullName();
  /**
   * <code>optional string fullName = 7;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>optional string fullName = 7;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
