// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

public interface AccountCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string number = 1;</code>
   */
  boolean hasNumber();
  /**
   * <code>required string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>required string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>optional int32 teamId = 2;</code>
   */
  boolean hasTeamId();
  /**
   * <code>optional int32 teamId = 2;</code>
   */
  int getTeamId();
}
