// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

public interface LoginInfoResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginInfoRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 transferable = 1;</code>
   */
  boolean hasTransferable();
  /**
   * <code>required int32 transferable = 1;</code>
   */
  int getTransferable();

  /**
   * <code>optional .LoginInfoRes.Token tokens = 2;</code>
   */
  boolean hasTokens();
  /**
   * <code>optional .LoginInfoRes.Token tokens = 2;</code>
   */
  org.whispersystems.textsecuregcm.internal.accounts.LoginInfoRes.Token getTokens();
  /**
   * <code>optional .LoginInfoRes.Token tokens = 2;</code>
   */
  org.whispersystems.textsecuregcm.internal.accounts.LoginInfoRes.TokenOrBuilder getTokensOrBuilder();

  /**
   * <code>optional string verificationCode = 3;</code>
   */
  boolean hasVerificationCode();
  /**
   * <code>optional string verificationCode = 3;</code>
   */
  java.lang.String getVerificationCode();
  /**
   * <code>optional string verificationCode = 3;</code>
   */
  com.google.protobuf.ByteString
      getVerificationCodeBytes();

  /**
   * <code>optional string account = 4;</code>
   */
  boolean hasAccount();
  /**
   * <code>optional string account = 4;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>optional string account = 4;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>optional bool requirePin = 5;</code>
   */
  boolean hasRequirePin();
  /**
   * <code>optional bool requirePin = 5;</code>
   */
  boolean getRequirePin();
}
