// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

public interface LoginInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string uid = 1;</code>
   */
  boolean hasUid();
  /**
   * <code>required string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>required string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>required string ua = 2;</code>
   */
  boolean hasUa();
  /**
   * <code>required string ua = 2;</code>
   */
  java.lang.String getUa();
  /**
   * <code>required string ua = 2;</code>
   */
  com.google.protobuf.ByteString
      getUaBytes();

  /**
   * <code>required bool supportTransfer = 3;</code>
   */
  boolean hasSupportTransfer();
  /**
   * <code>required bool supportTransfer = 3;</code>
   */
  boolean getSupportTransfer();
}
