// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

public interface TeamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TeamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string teams = 1;</code>
   */
  java.util.List<java.lang.String>
      getTeamsList();
  /**
   * <code>repeated string teams = 1;</code>
   */
  int getTeamsCount();
  /**
   * <code>repeated string teams = 1;</code>
   */
  java.lang.String getTeams(int index);
  /**
   * <code>repeated string teams = 1;</code>
   */
  com.google.protobuf.ByteString
      getTeamsBytes(int index);
}
