// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalAccountsService.proto

package org.whispersystems.textsecuregcm.internal.accounts;

/**
 * Protobuf type {@code UploadAvatarRequest}
 */
public  final class UploadAvatarRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UploadAvatarRequest)
    UploadAvatarRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadAvatarRequest.newBuilder() to construct.
  private UploadAvatarRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadAvatarRequest() {
    wuid_ = "";
    avatarContent_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UploadAvatarRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UploadAvatarRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            wuid_ = bs;
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            avatarContent_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_UploadAvatarRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_UploadAvatarRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.class, org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.Builder.class);
  }

  private int bitField0_;
  public static final int WUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object wuid_;
  /**
   * <code>required string wuid = 1;</code>
   */
  public boolean hasWuid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string wuid = 1;</code>
   */
  public java.lang.String getWuid() {
    java.lang.Object ref = wuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        wuid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string wuid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWuidBytes() {
    java.lang.Object ref = wuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATARCONTENT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString avatarContent_;
  /**
   * <code>required bytes avatarContent = 2;</code>
   */
  public boolean hasAvatarContent() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required bytes avatarContent = 2;</code>
   */
  public com.google.protobuf.ByteString getAvatarContent() {
    return avatarContent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasWuid()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAvatarContent()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wuid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, avatarContent_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wuid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, avatarContent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest)) {
      return super.equals(obj);
    }
    org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest other = (org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest) obj;

    if (hasWuid() != other.hasWuid()) return false;
    if (hasWuid()) {
      if (!getWuid()
          .equals(other.getWuid())) return false;
    }
    if (hasAvatarContent() != other.hasAvatarContent()) return false;
    if (hasAvatarContent()) {
      if (!getAvatarContent()
          .equals(other.getAvatarContent())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWuid()) {
      hash = (37 * hash) + WUID_FIELD_NUMBER;
      hash = (53 * hash) + getWuid().hashCode();
    }
    if (hasAvatarContent()) {
      hash = (37 * hash) + AVATARCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UploadAvatarRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UploadAvatarRequest)
      org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_UploadAvatarRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_UploadAvatarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.class, org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.Builder.class);
    }

    // Construct using org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      wuid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      avatarContent_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.internal_static_UploadAvatarRequest_descriptor;
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest getDefaultInstanceForType() {
      return org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest build() {
      org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest buildPartial() {
      org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest result = new org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.wuid_ = wuid_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.avatarContent_ = avatarContent_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest) {
        return mergeFrom((org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest other) {
      if (other == org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest.getDefaultInstance()) return this;
      if (other.hasWuid()) {
        bitField0_ |= 0x00000001;
        wuid_ = other.wuid_;
        onChanged();
      }
      if (other.hasAvatarContent()) {
        setAvatarContent(other.getAvatarContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasWuid()) {
        return false;
      }
      if (!hasAvatarContent()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object wuid_ = "";
    /**
     * <code>required string wuid = 1;</code>
     */
    public boolean hasWuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string wuid = 1;</code>
     */
    public java.lang.String getWuid() {
      java.lang.Object ref = wuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wuid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string wuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWuidBytes() {
      java.lang.Object ref = wuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string wuid = 1;</code>
     */
    public Builder setWuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      wuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string wuid = 1;</code>
     */
    public Builder clearWuid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      wuid_ = getDefaultInstance().getWuid();
      onChanged();
      return this;
    }
    /**
     * <code>required string wuid = 1;</code>
     */
    public Builder setWuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      wuid_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString avatarContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes avatarContent = 2;</code>
     */
    public boolean hasAvatarContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bytes avatarContent = 2;</code>
     */
    public com.google.protobuf.ByteString getAvatarContent() {
      return avatarContent_;
    }
    /**
     * <code>required bytes avatarContent = 2;</code>
     */
    public Builder setAvatarContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      avatarContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes avatarContent = 2;</code>
     */
    public Builder clearAvatarContent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      avatarContent_ = getDefaultInstance().getAvatarContent();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UploadAvatarRequest)
  }

  // @@protoc_insertion_point(class_scope:UploadAvatarRequest)
  private static final org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest();
  }

  public static org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<UploadAvatarRequest>
      PARSER = new com.google.protobuf.AbstractParser<UploadAvatarRequest>() {
    @java.lang.Override
    public UploadAvatarRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UploadAvatarRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UploadAvatarRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadAvatarRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.whispersystems.textsecuregcm.internal.accounts.UploadAvatarRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

