// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.whispersystems.textsecuregcm.internal.common;

public interface BaseAnyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BaseAnyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string value = 1;</code>
   */
  boolean hasValue();
  /**
   * <code>required string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>required string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
