// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.whispersystems.textsecuregcm.internal.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Step_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Step_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseAnyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseAnyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\032\031google/protobuf/any.prot" +
      "o\"\007\n\005Empty\"\222\001\n\004Step\022\016\n\006offset\030\001 \002(\r\022\016\n\006l" +
      "ength\030\002 \002(\r\022\016\n\006number\030\003 \001(\t\022\r\n\005email\030\004 \001" +
      "(\t\022\014\n\004name\030\005 \001(\t\022\017\n\007teamsId\030\006 \001(\004\022\020\n\010dis" +
      "abled\030\007 \003(\010\022\r\n\005appid\030\010 \001(\t\022\013\n\003pid\030\t \001(\t\"" +
      "_\n\014BaseResponse\022\013\n\003ver\030\001 \002(\r\022\016\n\006status\030\002" +
      " \002(\r\022\016\n\006reason\030\003 \001(\t\022\"\n\004data\030\004 \001(\0132\024.goo" +
      "gle.protobuf.Any\" \n\017BaseAnyResponse\022\r\n\005v" +
      "alue\030\001 \002(\t*\247\004\n\006STATUS\022\006\n\002OK\020\000\022\025\n\021INVALID" +
      "_PARAMETER\020\001\022\021\n\rNO_PERMISSION\020\002\022\021\n\rNO_SU" +
      "CH_GROUP\020\003\022\030\n\024NO_SUCH_GROUP_MEMBER\020\004\022\021\n\r" +
      "INVALID_TOKEN\020\005\022\031\n\025SERVER_INTERNAL_ERROR" +
      "\020\006\022\036\n\032NO_SUCH_GROUP_ANNOUNCEMENT\020\007\022\020\n\014GR" +
      "OUP_EXISTS\020\010\022\020\n\014NO_SUCH_FILE\020\t\022\034\n\030GROUP_" +
      "IS_FULL_OR_EXCEEDS\020\n\022\020\n\014NO_SUCH_USER\020\013\022\027" +
      "\n\023RATE_LIMIT_EXCEEDED\020\014\022\023\n\017INVALID_INVIT" +
      "ER\020\r\022\024\n\020USER_IS_DISABLED\020\016\022\027\n\023PUID_IS_RE" +
      "GISTERING\020\017\022 \n\034NUMBER_IS_BINDING_OTHER_P" +
      "UID\020\020\022\024\n\020TEAM_HAS_MEMBERS\020\021\022\022\n\016VOTE_IS_C" +
      "LOSED\020\022\022\025\n\021NO_SUCH_GROUP_PIN\020\023\022\024\n\020USER_E" +
      "MAIL_EXIST\020\024\022\025\n\021USER_OKTAID_EXIST\020\025\022\036\n\032G" +
      "ROUP_PIN_CONTENT_TOO_LONG\020\026\022\017\n\013OTHER_ERR" +
      "OR\020cB<\n0org.whispersystems.textsecuregcm" +
      ".internal.commonP\001Z\006/proto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Step_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Step_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Step_descriptor,
        new java.lang.String[] { "Offset", "Length", "Number", "Email", "Name", "TeamsId", "Disabled", "Appid", "Pid", });
    internal_static_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseResponse_descriptor,
        new java.lang.String[] { "Ver", "Status", "Reason", "Data", });
    internal_static_BaseAnyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BaseAnyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseAnyResponse_descriptor,
        new java.lang.String[] { "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
