// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupService.proto

package org.whispersystems.textsecuregcm.internal.groups;

public interface GroupsAnnouncementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupsAnnouncementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string content = 1;</code>
   */
  boolean hasContent();
  /**
   * <code>required string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>required string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>required string gid = 2;</code>
   */
  boolean hasGid();
  /**
   * <code>required string gid = 2;</code>
   */
  java.lang.String getGid();
  /**
   * <code>required string gid = 2;</code>
   */
  com.google.protobuf.ByteString
      getGidBytes();
}
