// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupService.proto

package org.whispersystems.textsecuregcm.internal.groups;

public final class GroupServiceOuterClass {
  private GroupServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KickoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KickoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KickoutResponse_ResultInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KickoutResponse_ResultInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupMemberInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupMemberInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupsAnnouncementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupsAnnouncementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupMembersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupMembersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupAvatarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupAvatarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupJoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupJoinRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022GroupService.proto\032\014common.proto\032\035Inte" +
      "rnalAccountsService.proto\"q\n\017KickoutResp" +
      "onse\0220\n\013resultInfos\030\001 \003(\0132\033.KickoutRespo" +
      "nse.ResultInfo\032,\n\nResultInfo\022\016\n\006number\030\001" +
      " \002(\t\022\016\n\006result\030\002 \001(\t\"\211\002\n\nGroupsInfo\022\n\n\002i" +
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007creator\030\003 \001(\t\022\022" +
      "\n\ncreateTime\030\004 \001(\003\022\016\n\006status\030\005 \001(\005\022\025\n\rme" +
      "ssageExpiry\030\006 \001(\003\022\016\n\006avatar\030\007 \001(\t\022\017\n\007ver" +
      "sion\030\010 \001(\005\022\026\n\016invitationRule\030\t \001(\005\022\026\n\016la" +
      "stActiveTime\030\n \001(\003\022\r\n\005owner\030\013 \001(\t\022\017\n\007bac" +
      "kup1\030\014 \001(\t\022\017\n\007backup2\030\r \001(\t\022\023\n\013remindCyc" +
      "le\030\016 \001(\t\"\307\001\n\017GroupMemberInfo\022\013\n\003uid\030\001 \002(" +
      "\t\022\013\n\003gid\030\002 \002(\t\022\014\n\004role\030\003 \001(\t\022\016\n\006avatar\030\004" +
      " \001(\t\022\017\n\007inviter\030\005 \001(\t\022\021\n\tplainName\030\006 \001(\t" +
      "\022\023\n\013displayName\030\007 \001(\t\022\016\n\006remark\030\010 \001(\t\022\024\n" +
      "\014notification\030\t \001(\t\022\r\n\005email\030\n \001(\t\022\016\n\006ok" +
      "taId\030\013 \001(\t\"D\n\rGroupsRequest\022\023\n\004step\030\001 \001(" +
      "\0132\005.Step\022\036\n\tgroupInfo\030\002 \001(\0132\013.GroupsInfo" +
      "\"@\n\016GroupsResponse\022\r\n\005total\030\001 \001(\004\022\037\n\ngro" +
      "upsInfo\030\002 \003(\0132\013.GroupsInfo\"G\n\023GroupsCrea" +
      "teRequest\022\037\n\ngroupsInfo\030\001 \002(\0132\013.GroupsIn" +
      "fo\022\017\n\007members\030\002 \003(\t\"9\n\031GroupsAnnouncemen" +
      "tRequest\022\017\n\007content\030\001 \002(\t\022\013\n\003gid\030\002 \002(\t\"A" +
      "\n\024GroupMembersResponse\022)\n\017groupMemberInf" +
      "o\030\001 \003(\0132\020.GroupMemberInfo\"J\n\022GroupAvatar" +
      "Request\022\013\n\003gid\030\001 \002(\t\022\020\n\010operator\030\002 \002(\t\022\025" +
      "\n\ravatarContent\030\003 \002(\014\"D\n\020GroupJoinReques" +
      "t\0220\n\022groupCreateRequest\030\001 \003(\0132\024.GroupsCr" +
      "eateRequest2\322\004\n\014GroupService\0225\n\026kickoutA" +
      "llGroupForUser\022\014.UidsRequest\032\r.BaseRespo" +
      "nse\022)\n\006getAll\022\016.GroupsRequest\032\017.GroupsRe" +
      "sponse\022-\n\006create\022\024.GroupsCreateRequest\032\r" +
      ".BaseResponse\022+\n\004join\022\024.GroupsCreateRequ" +
      "est\032\r.BaseResponse\022,\n\005leave\022\024.GroupsCrea" +
      "teRequest\032\r.BaseResponse\022%\n\004edit\022\016.Group" +
      "sRequest\032\r.BaseResponse\0229\n\014announcement\022" +
      "\032.GroupsAnnouncementRequest\032\r.BaseRespon" +
      "se\0220\n\017getGroupMembers\022\016.GroupsRequest\032\r." +
      "BaseResponse\022,\n\013getMyGroups\022\016.GroupsRequ" +
      "est\032\r.BaseResponse\0222\n\nchangeRole\022\025.Group" +
      "MembersResponse\032\r.BaseResponse\022,\n\010bulkJo" +
      "in\022\021.GroupJoinRequest\032\r.BaseResponse\0222\n\014" +
      "uploadAvatar\022\023.GroupAvatarRequest\032\r.Base" +
      "ResponseB4\n0org.whispersystems.textsecur" +
      "egcm.internal.groupsP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.whispersystems.textsecuregcm.internal.common.Common.getDescriptor(),
          org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.getDescriptor(),
        });
    internal_static_KickoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KickoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KickoutResponse_descriptor,
        new java.lang.String[] { "ResultInfos", });
    internal_static_KickoutResponse_ResultInfo_descriptor =
      internal_static_KickoutResponse_descriptor.getNestedTypes().get(0);
    internal_static_KickoutResponse_ResultInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KickoutResponse_ResultInfo_descriptor,
        new java.lang.String[] { "Number", "Result", });
    internal_static_GroupsInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GroupsInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Creator", "CreateTime", "Status", "MessageExpiry", "Avatar", "Version", "InvitationRule", "LastActiveTime", "Owner", "Backup1", "Backup2", "RemindCycle", });
    internal_static_GroupMemberInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GroupMemberInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupMemberInfo_descriptor,
        new java.lang.String[] { "Uid", "Gid", "Role", "Avatar", "Inviter", "PlainName", "DisplayName", "Remark", "Notification", "Email", "OktaId", });
    internal_static_GroupsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GroupsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsRequest_descriptor,
        new java.lang.String[] { "Step", "GroupInfo", });
    internal_static_GroupsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GroupsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsResponse_descriptor,
        new java.lang.String[] { "Total", "GroupsInfo", });
    internal_static_GroupsCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GroupsCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsCreateRequest_descriptor,
        new java.lang.String[] { "GroupsInfo", "Members", });
    internal_static_GroupsAnnouncementRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GroupsAnnouncementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupsAnnouncementRequest_descriptor,
        new java.lang.String[] { "Content", "Gid", });
    internal_static_GroupMembersResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GroupMembersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupMembersResponse_descriptor,
        new java.lang.String[] { "GroupMemberInfo", });
    internal_static_GroupAvatarRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GroupAvatarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupAvatarRequest_descriptor,
        new java.lang.String[] { "Gid", "Operator", "AvatarContent", });
    internal_static_GroupJoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GroupJoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupJoinRequest_descriptor,
        new java.lang.String[] { "GroupCreateRequest", });
    org.whispersystems.textsecuregcm.internal.common.Common.getDescriptor();
    org.whispersystems.textsecuregcm.internal.accounts.InternalAccountsServiceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
