// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupService.proto

package org.whispersystems.textsecuregcm.internal.groups;

public interface GroupAvatarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GroupAvatarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string gid = 1;</code>
   */
  boolean hasGid();
  /**
   * <code>required string gid = 1;</code>
   */
  java.lang.String getGid();
  /**
   * <code>required string gid = 1;</code>
   */
  com.google.protobuf.ByteString
      getGidBytes();

  /**
   * <code>required string operator = 2;</code>
   */
  boolean hasOperator();
  /**
   * <code>required string operator = 2;</code>
   */
  java.lang.String getOperator();
  /**
   * <code>required string operator = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperatorBytes();

  /**
   * <code>required bytes avatarContent = 3;</code>
   */
  boolean hasAvatarContent();
  /**
   * <code>required bytes avatarContent = 3;</code>
   */
  com.google.protobuf.ByteString getAvatarContent();
}
